import type { Metadata } from "next";
import { Manrope } from "next/font/google";
import "./globals.css";
import NumberInputWheelGuard from "@/components/layout/NumberInputWheelGuard";
import Navbar from "@/components/layout/Navbar";
import { AuthProvider } from "@/contexts/AuthContext";
import { EquipoProvider } from "@/contexts/EquipoContext";
import { TareasProvider } from "@/contexts/TareasContext";
import { LevantamientoCatalogoProvider } from "@/contexts/LevantamientoCatalogoContext";
import { MaterialesProvider } from "@/contexts/MaterialesContext";
import { runtimeConfigWarnings } from "@/lib/runtime-config-guard";

const manrope = Manrope({
  variable: "--font-manrope",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Kuche Plataforma",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  if (typeof window === "undefined" && runtimeConfigWarnings.length > 0) {
    console.warn("[runtime-config]", runtimeConfigWarnings);
  }

  return (
    <html lang="es">
      <body className={`${manrope.variable} font-sans antialiased`}>
        <AuthProvider>
          <EquipoProvider>
            <TareasProvider>
              <LevantamientoCatalogoProvider>
                <MaterialesProvider>
                  <NumberInputWheelGuard />
                  <Navbar />
                  {children}
                </MaterialesProvider>
              </LevantamientoCatalogoProvider>
            </TareasProvider>
          </EquipoProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
