import type { Metadata } from "next";
import { Manrope } from "next/font/google";
import "./globals.css";
import NumberInputWheelGuard from "@/components/layout/NumberInputWheelGuard";
import Navbar from "@/components/layout/Navbar";
import { AuthProvider } from "@/contexts/AuthContext";
import { runtimeConfigWarnings } from "@/lib/runtime-config-guard";

const manrope = Manrope({
  variable: "--font-manrope",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Kuche Plataforma",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  if (typeof window === "undefined" && runtimeConfigWarnings.length > 0) {
    console.warn("[runtime-config]", runtimeConfigWarnings);
  }

  return (
    <html lang="es">
      <body className={`${manrope.variable} font-sans antialiased`}>
        <AuthProvider>
          <NumberInputWheelGuard />
          <Navbar />
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}
